ignored = [
  "github.com/hashicorp/terraform/backend*",
  "github.com/hashicorp/nomad*"
]

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.10.0"

[[constraint]]
  name = "gopkg.in/ns1/ns1-go.v2"
  revision = "85a531ec65f1335ab7b2239bbfc8cb4a3bace9c5"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "v1.0.0"

[prune]
  go-tests = true
  unused-packages = true
